import type { MetadataRoute } from "next";

import { siteUrl } from "@/lib/config";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    "",
    "/how-it-works",
    "/assets",
    "/technology",
    "/platform-infrastructure",
    "/gemstone-programs",
    "/asset-registry",
    "/aquamarine",
    "/emerald",
    "/peridot",
    "/ruby",
    "/tourmaline",
    "/natural-raw-charoite",
    "/natural-rough-alexandrite",
    "/natural-rough-aquamarine",
    "/natural-rough-chrysoprase",
    "/natural-rough-italian-jade",
    "/natural-rough-jasper",
    "/natural-rough-ruby-c-quality",
    "/natural-rough-ruby-trapiche",
    "/natural-rough-ruby-gem-quality",
    "/natural-rough-rutilated-quartz",
    "/natural-rough-tourmaline",
    "/natural-rough-peridot",
    "/natural-rough-emerald",
    "/redemption-portal",
    "/gemstone-tokenization",
    "/physical-redemption",
    "/digital-asset-passports",
    "/enterprise",
    "/enterprise-tokenization",
    "/gemstone-owners",
    "/gemstone-buyers",
    "/licensing-white-label",
    "/future-infrastructure",
    "/investors",
    "/about",
    "/governance",
    "/contact",
    "/program-overview",
    "/discount-methodology",
    "/token-acquisition",
    "/restricted-jurisdictions",
    "/early-participation",
    "/eligibility-kyc",
    "/faq",
    "/independent-verification",
    "/custody-vault-structure",
    "/proof-of-reserves",
    "/corporate-development",
    "/news",
    "/resources",
    "/documents",
    "/whitepaper",
    "/risk-disclosure",
    "/anti-fraud-notice",
    "/participant-portal",
    "/early-participation-program",
  ].map((path) => ({
    url: `${siteUrl}${path}`,
    lastModified: new Date("2026-08-28"),
    changeFrequency: path ? "monthly" : "weekly",
    priority: path ? 0.8 : 1,
  }));
}
